before_build:
  - nuget restore
  
install:
  - git submodule update --init --recursive
  
cache:
  - packages -> **\packages.config
  
build:
  parallel: true                  # enable MSBuild parallel builds
  project: Sidekick.sln           # path to Visual Studio solution or project