install:
  - git submodule update --init --recursive
  - nuget restore libs/SQLite.Net-PCL/SQLite.Net.OSS.sln
  - nuget restore libs/Orc.FilterBuilder/src/Orc.FilterBuilder.sln

before_build:
  - nuget restore Sidekick.OSS.sln

cache:
  - packages -> **\packages.config

build:
  parallel: true                      # enable MSBuild parallel builds
  project: Sidekick.OSS.sln           # path to Visual Studio solution or project