//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.SpacedRepetition.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.SpacedRepetition.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaced Repetition.
        /// </summary>
        internal static string SpacedRepetition_Card_GroupedHeader_SpacedRepetition {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_GroupedHeader_SpacedRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string SpacedRepetition_Card_GroupedHeader_State {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_GroupedHeader_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        internal static string SpacedRepetition_Card_GroupedHeader_Times {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_GroupedHeader_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_Data {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_Due {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_EFactor {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_EFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_Id {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_Interval {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lapses.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_Lapses {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_Lapses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_LastModified {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc State.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_MiscState {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_MiscState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_PracticeState {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_PracticeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string SpacedRepetition_Card_Header_Reviews {
            get {
                return ResourceManager.GetString("SpacedRepetition_Card_Header_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string SpacedRepetition_Grade_Easy {
            get {
                return ResourceManager.GetString("SpacedRepetition_Grade_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string SpacedRepetition_Grade_Fail {
            get {
                return ResourceManager.GetString("SpacedRepetition_Grade_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail (Medium).
        /// </summary>
        internal static string SpacedRepetition_Grade_FailMedium {
            get {
                return ResourceManager.GetString("SpacedRepetition_Grade_FailMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail (Severe).
        /// </summary>
        internal static string SpacedRepetition_Grade_FailSevere {
            get {
                return ResourceManager.GetString("SpacedRepetition_Grade_FailSevere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string SpacedRepetition_Grade_Good {
            get {
                return ResourceManager.GetString("SpacedRepetition_Grade_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string SpacedRepetition_Grade_Hard {
            get {
                return ResourceManager.GetString("SpacedRepetition_Grade_Hard", resourceCulture);
            }
        }
    }
}
